---
version: '3.7'
services:

  build_service:
    build: build_file
    volumes:
      - app-volume:target

  web_service:
    image: tomcat:11.0.0-jdk17
    volumes:
      - app-volume:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - build_service
          
volumes:
     app-volume:     
